# Generated by Django 3.2.9 on 2022-01-18 07:07

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import portfolio.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to=portfolio.utilities.get_cover_path, verbose_name='Cover')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(upload_to=portfolio.utilities.get_thumbnail_path, verbose_name='Thumbnail')),
                ('description', models.TextField(verbose_name='Description')),
                ('code_url', models.URLField(verbose_name='Code URL')),
                ('project_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-end_date', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.utilities.get_image_path, verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['project', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский')], max_length=2, verbose_name='Language')),
                ('description', models.TextField(verbose_name='Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Translation',
                'verbose_name_plural': 'Project Translations',
                'ordering': ['project', 'language'],
                'unique_together': {('project', 'language')},
            },
        ),
    ]
